import { Product, Order, User, FAQ } from '@/types';

// Dummy Products
export const products: Product[] = [
  {
    id: '1',
    name: 'Whey Protein Isolate',
    description: 'Premium whey protein isolate with 25g protein per serving. Perfect for post-workout recovery.',
    price: 49.99,
    category: 'protein',
    imageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500',
    stock: 150,
    brand: 'ProFit',
    rating: 4.8,
    reviewCount: 342,
    featured: true,
  },
  {
    id: '2',
    name: 'Creatine Monohydrate',
    description: 'Pure micronized creatine monohydrate for strength and muscle gains.',
    price: 29.99,
    category: 'creatine',
    imageUrl: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=500',
    stock: 200,
    brand: 'MuscleTech',
    rating: 4.9,
    reviewCount: 567,
    featured: true,
  },
  {
    id: '3',
    name: 'Pre-Workout Extreme',
    description: 'High-energy pre-workout formula with caffeine, beta-alanine, and citrulline.',
    price: 39.99,
    category: 'pre-workout',
    imageUrl: 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=500',
    stock: 120,
    brand: 'Energize',
    rating: 4.6,
    reviewCount: 234,
    featured: true,
  },
  {
    id: '4',
    name: 'BCAA Recovery',
    description: 'Branch chain amino acids for muscle recovery and endurance.',
    price: 34.99,
    category: 'amino-acids',
    imageUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
    stock: 180,
    brand: 'RecoverMax',
    rating: 4.7,
    reviewCount: 189,
    featured: false,
  },
  {
    id: '5',
    name: 'Multivitamin Complex',
    description: 'Complete daily multivitamin with essential vitamins and minerals.',
    price: 24.99,
    category: 'vitamins',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/81/Maltose_syrup.jpg',
    stock: 300,
    brand: 'VitaLife',
    rating: 4.5,
    reviewCount: 421,
    featured: false,
  },
  {
    id: '6',
    name: 'Fat Burner Pro',
    description: 'Thermogenic fat burner with green tea extract and L-carnitine.',
    price: 44.99,
    category: 'weight-loss',
    imageUrl: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=500',
    stock: 90,
    brand: 'LeanBody',
    rating: 4.3,
    reviewCount: 156,
    featured: false,
  },
  {
    id: '7',
    name: 'Omega-3 Fish Oil',
    description: 'High-quality omega-3 fatty acids for heart and brain health.',
    price: 19.99,
    category: 'health',
    imageUrl: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=500',
    stock: 250,
    brand: 'OceanPure',
    rating: 4.8,
    reviewCount: 389,
    featured: false,
  },
  {
    id: '8',
    name: 'Casein Protein',
    description: 'Slow-digesting protein perfect for nighttime recovery.',
    price: 54.99,
    category: 'protein',
    imageUrl: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=500',
    stock: 110,
    brand: 'ProFit',
    rating: 4.7,
    reviewCount: 278,
    featured: false,
  },
];

// Dummy Users
export const users: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@supplementstore.com',
    role: 'admin',
  },
  {
    id: '2',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'user',
  },
];

// Dummy Orders - will be populated with user orders
export const orders: Order[] = [
  {
    id: 'ORD-001',
    userId: '2',
    userName: 'John Doe',
    userEmail: 'john@example.com',
    userPhone: '+1 (555) 123-4567',
    items: [
      {
        productId: '1',
        productName: 'Whey Protein Isolate',
        productImage: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500',
        quantity: 1,
        price: 49.99,
      },
      {
        productId: '2',
        productName: 'Creatine Monohydrate',
        productImage: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=500',
        quantity: 1,
        price: 29.99,
      },
    ],
    subtotal: 79.98,
    shipping: 5.99,
    tax: 6.40,
    total: 92.37,
    status: 'delivered',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), // 10 days ago
    shippingAddress: {
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
    },
  },
  {
    id: 'ORD-002',
    userId: '2',
    userName: 'John Doe',
    userEmail: 'john@example.com',
    userPhone: '+1 (555) 123-4567',
    items: [
      {
        productId: '3',
        productName: 'Pre-Workout Extreme',
        productImage: 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=500',
        quantity: 1,
        price: 39.99,
      },
    ],
    subtotal: 39.99,
    shipping: 5.99,
    tax: 3.20,
    total: 49.18,
    status: 'shipped',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    shippingAddress: {
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
    },
  },
  {
    id: 'ORD-003',
    userId: '3',
    userName: 'Jane Smith',
    userEmail: 'jane@example.com',
    userPhone: '+1 (555) 987-6543',
    items: [
      {
        productId: '5',
        productName: 'Multivitamin Complex',
        productImage: 'https://images.unsplash.com/photo-1550572017-4814c6f5a5e6?w=500',
        quantity: 1,
        price: 24.99,
      },
      {
        productId: '7',
        productName: 'Omega-3 Fish Oil',
        productImage: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=500',
        quantity: 1,
        price: 19.99,
      },
    ],
    subtotal: 44.98,
    shipping: 5.99,
    tax: 3.60,
    total: 54.57,
    status: 'processing',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    shippingAddress: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
      country: 'USA',
    },
  },
  {
    id: 'ORD-004',
    userId: '4',
    userName: 'Mike Johnson',
    userEmail: 'mike@example.com',
    userPhone: '+1 (555) 456-7890',
    items: [
      {
        productId: '1',
        productName: 'Whey Protein Isolate',
        productImage: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500',
        quantity: 1,
        price: 49.99,
      },
      {
        productId: '4',
        productName: 'BCAA Recovery',
        productImage: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
        quantity: 1,
        price: 34.99,
      },
    ],
    subtotal: 84.98,
    shipping: 0,
    tax: 6.80,
    total: 91.78,
    status: 'pending',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    shippingAddress: {
      street: '789 Pine Rd',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      country: 'USA',
    },
  },
  {
    id: 'ORD-005',
    userId: '5',
    userName: 'Sarah Williams',
    userEmail: 'sarah@example.com',
    userPhone: '+1 (555) 321-0987',
    items: [
      {
        productId: '6',
        productName: 'Fat Burner Pro',
        productImage: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=500',
        quantity: 1,
        price: 44.99,
      },
    ],
    subtotal: 44.99,
    shipping: 5.99,
    tax: 3.60,
    total: 54.58,
    status: 'cancelled',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), // 8 days ago
    shippingAddress: {
      street: '321 Elm St',
      city: 'Miami',
      state: 'FL',
      zipCode: '33101',
      country: 'USA',
    },
  },
  {
    id: 'ORD-006',
    userId: '6',
    userName: 'Robert Chen',
    userEmail: 'robert@example.com',
    userPhone: '+1 (555) 789-0123',
    items: [
      {
        productId: '8',
        productName: 'Casein Protein',
        productImage: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=500',
        quantity: 1,
        price: 54.99,
      },
      {
        productId: '3',
        productName: 'Pre-Workout Extreme',
        productImage: 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=500',
        quantity: 1,
        price: 39.99,
      },
    ],
    subtotal: 94.98,
    shipping: 0,
    tax: 7.60,
    total: 102.58,
    status: 'delivered',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(), // 20 days ago
    shippingAddress: {
      street: '789 Market St',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      country: 'USA',
    },
  },
  {
    id: 'ORD-007',
    userId: '7',
    userName: 'Emily Davis',
    userEmail: 'emily@example.com',
    userPhone: '+1 (555) 456-7891',
    items: [
      {
        productId: '4',
        productName: 'BCAA Recovery',
        productImage: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
        quantity: 1,
        price: 34.99,
      },
    ],
    subtotal: 34.99,
    shipping: 5.99,
    tax: 2.80,
    total: 43.78,
    status: 'shipped',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
    shippingAddress: {
      street: '456 Broadway',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
      country: 'USA',
    },
  },
  {
    id: 'ORD-008',
    userId: '8',
    userName: 'Michael Brown',
    userEmail: 'michael@example.com',
    userPhone: '+1 (555) 234-5678',
    items: [
      {
        productId: '1',
        productName: 'Whey Protein Isolate',
        productImage: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500',
        quantity: 1,
        price: 49.99,
      },
      {
        productId: '5',
        productName: 'Multivitamin Complex',
        productImage: 'https://images.unsplash.com/photo-1550572017-4814c6f5a5e6?w=500',
        quantity: 1,
        price: 24.99,
      },
      {
        productId: '7',
        productName: 'Omega-3 Fish Oil',
        productImage: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=500',
        quantity: 1,
        price: 19.99,
      },
    ],
    subtotal: 94.97,
    shipping: 0,
    tax: 7.60,
    total: 102.57,
    status: 'processing',
    createdAt: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString(), // 12 hours ago
    shippingAddress: {
      street: '123 Oak Lane',
      city: 'Austin',
      state: 'TX',
      zipCode: '78701',
      country: 'USA',
    },
  },
  {
    id: 'ORD-009',
    userId: '9',
    userName: 'Lisa Anderson',
    userEmail: 'lisa@example.com',
    userPhone: '+1 (555) 876-5432',
    items: [
      {
        productId: '2',
        productName: 'Creatine Monohydrate',
        productImage: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=500',
        quantity: 1,
        price: 29.99,
      },
      {
        productId: '4',
        productName: 'BCAA Recovery',
        productImage: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500',
        quantity: 1,
        price: 34.99,
      },
    ],
    subtotal: 64.98,
    shipping: 0,
    tax: 5.20,
    total: 70.18,
    status: 'pending',
    createdAt: new Date(Date.now() - 0.1 * 24 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    shippingAddress: {
      street: '789 Pine Ave',
      city: 'Denver',
      state: 'CO',
      zipCode: '80202',
      country: 'USA',
    },
  },
  {
    id: 'ORD-010',
    userId: '10',
    userName: 'David Wilson',
    userEmail: 'david@example.com',
    userPhone: '+1 (555) 345-6789',
    items: [
      {
        productId: '6',
        productName: 'Fat Burner Pro',
        productImage: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=500',
        quantity: 1,
        price: 44.99,
      },
      {
        productId: '3',
        productName: 'Pre-Workout Extreme',
        productImage: 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=500',
        quantity: 1,
        price: 39.99,
      },
    ],
    subtotal: 84.98,
    shipping: 0,
    tax: 6.80,
    total: 91.78,
    status: 'delivered',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), // 15 days ago
    shippingAddress: {
      street: '321 Maple Dr',
      city: 'Boston',
      state: 'MA',
      zipCode: '02101',
      country: 'USA',
    },
  },
];

// FAQ Data
export const faqs: FAQ[] = [
  {
    id: '1',
    question: 'What are your shipping options?',
    answer: 'We offer free standard shipping on orders over $50. Standard shipping takes 5-7 business days. Express shipping (2-3 business days) is available for $9.99, and overnight shipping is available for $19.99.',
  },
  {
    id: '2',
    question: 'Are your products tested for quality?',
    answer: 'Yes, all our supplements are third-party tested for purity and potency. We work with certified laboratories to ensure our products meet the highest quality standards and are free from contaminants.',
  },
  {
    id: '3',
    question: 'What is your return policy?',
    answer: 'We offer a 30-day money-back guarantee on all products. If you\'re not satisfied with your purchase, you can return it within 30 days for a full refund. The product must be unopened and in its original packaging.',
  },
  {
    id: '4',
    question: 'How should I store my supplements?',
    answer: 'Store supplements in a cool, dry place away from direct sunlight. Keep containers tightly closed when not in use. Most supplements should be stored at room temperature (68-77°F). Check individual product labels for specific storage instructions.',
  },
  {
    id: '5',
    question: 'Can I take multiple supplements together?',
    answer: 'Many supplements can be taken together, but it\'s important to consult with a healthcare professional before combining supplements, especially if you\'re taking medications. Some supplements may interact with each other or with medications.',
  },
  {
    id: '6',
    question: 'Do you offer international shipping?',
    answer: 'Currently, we only ship within the United States. We\'re working on expanding our shipping options to include international destinations in the near future. Sign up for our newsletter to be notified when international shipping becomes available.',
  },
];

// Current user (can be switched between admin and regular user)
export let currentUser: User = users[1]; // Default to regular user

export const setCurrentUser = (user: User) => {
  currentUser = user;
};

